global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web_ban_hang_online_app'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['app:8084']